export const sidebardata = [
	{
		id: 1,
		title: "Dashboard",
		path: "/",
		icon: <i className="fas fa-tachometer-alt"></i>,
		management: false,
	},
	{
		id: 2,
		title: "Users",
		path: "/users",
		icon: <i className="fas fa-users"></i>,
		management: false,
		admin: true,
	},

	{
		id: 3,
		title: "Services",
		path: "/Services",
		icon: <i className="fas fa-calendar-alt"></i>,
		management: false,
	},
	{
		id: 4,
		title: "Veterinarians",
		path: "/Veterinarians",
		icon: <i className="fas fa-hotel"></i>,
		management: false,
	},
	{
		id: 5,
		title: "Blogs",
		path: "/blogs",
		icon: <i className="fas fa-blog"></i>,
		management: false,
	},
	{
		id: 6,
		title: "Products",
		path: "/products",
		icon: <i className="fas fa-trophy"></i>,
        management: false,
	},
	{
		id: 7,
		title: "Messages",
		path: "/messages",
		icon: <i className="fas fa-chart-line"></i>,
		management: false,
	},
	{
		id: 8,
		title: "Contact Us Inquiries",
		path: "/contactUsInquiries",
		icon: <i className="fas fa-envelope"></i>,
		management: false,
	},
	{
		id: 9,
		title: "Animal Gallery",
		icon: <i className="fas fa-images"></i>,
		path: "/animalGallery",
		management: false,
	},
	{
		id: 10,
		title: "subscribers",
		icon : <i className="fas fa-users"></i>,
		path: "/subscribers",
		management: false,
	},
	{
		id: 11,
		title: "Pricings",
		icon: <i className="fas fa-dollar-sign"></i>,
		path: "/pricings",
		management: false,

	},
	{
		id: 12,
		title: "Payments",
		path: "/payments",
		icon: <i className="fas fa-dollar-sign"></i>,
		management: false,
	},
];
